language: c
sudo: false
dist: xenial

matrix:
  include:
    - os: linux
      arch: amd64
      compiler: clang
    - os: linux
      arch: amd64
      compiler: gcc
    - os: linux
      arch: arm64
      compiler: gcc
    - os: osx
      arch: amd64
      compiler: clang

script: make
